# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
# Build + clean for the encrypted polygenic-risk-scoring app.
# Build runs inside the FHE-dev container (use ./run-in-container.sh "make build");
# clean runs on the host.

NBC = cd /opt/niobium-client/dsl_fhe && python3 -m xcomp.nbc

.PHONY: build clean help install-skill

help:
	@echo "Targets:"
	@echo "  install-skill  fetch the fhe-application-design skill from GitHub into the repo-root"
	@echo "                 .claude/skills/ and .agents/skills/ (shared by all apps)"
	@echo "  build          compile .niob -> nb_out/ and build the binaries (run in-container)"
	@echo "  clean          remove build trees, run homes, and recorded traces (host)"

# Install the fhe-application-design skill from GitHub into BOTH .claude/skills/
# and .agents/skills/ (Claude Code and the open agent-skills layout), so this is
# not a Claude-only setup. A SINGLE install lives at the repository root and is
# shared by every app, so running this target from inside an app still installs
# it at the root (SKILL_ROOT resolves to the git top level, falling back to ..).
# The skill bundles the Docker build context under environment/. Both directories
# are gitignored.
SKILL_REPO ?= https://github.com/NiobiumInc/niobium-skills
SKILL_NAME ?= fhe-application-design
SKILL_ROOT ?= $(shell git rev-parse --show-toplevel 2>/dev/null || echo ..)
install-skill:
	@tmp=$$(mktemp -d) && git clone --depth 1 $(SKILL_REPO) "$$tmp/ns" && \
	for d in "$(SKILL_ROOT)/.claude/skills" "$(SKILL_ROOT)/.agents/skills"; do \
	  mkdir -p "$$d" && rm -rf "$$d/$(SKILL_NAME)" && \
	  cp -R "$$tmp/ns/skills/$(SKILL_NAME)" "$$d/$(SKILL_NAME)" && \
	  echo "installed skill to $$d/$(SKILL_NAME)"; \
	done; rm -rf "$$tmp"

build:
	$(NBC) compile /work/shared.niob /work/client.niob /work/server.niob --outdir /work/nb_out
	cmake -S /work/nb_out -B /work/nb_out/build -DCMAKE_BUILD_TYPE=Release \
	    -DNIOBIUM_CLIENT_ROOT=/opt/niobium-client
	cmake --build /work/nb_out/build -j$$(nproc)

# NOTE: run-home directories are listed EXPLICITLY — never `rm -rf run_*`,
# which would also match (and delete) run_test.sh / run-in-container.sh.
clean:
	rm -rf nb_out/build
	rm -rf run_cpu run_sim run_sim-full run_fog run_smoke run_demo
	rm -rf score_profile_* fhetch_driver_source_*
