#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
set -euo pipefail
if [ $# -eq 0 ] || [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  cat <<'EOF'
run-in-container.sh: run a command inside the FHE-dev image with this
project mounted at /work (and ~/.fog mounted when present, for Fog runs).

Common invocations:
  ./run-in-container.sh "python3 harness/gen_data.py"        # regenerate data
  ./run-in-container.sh "python3 harness/prepare_inputs.py"  # pack + export model
  ./run-in-container.sh "make build"                         # compile + build
  ./run-in-container.sh "./run_test.sh"                      # DEFAULT: the Niobium Fog
  ./run-in-container.sh "./run_test.sh --cpu"                # local OpenFHE validation
  ./run-in-container.sh "./run_test.sh --sim"                # local trace-simulator validation
  ./run-in-container.sh "python3 harness/demo_two_process.py"   # client/server demo
EOF
  exit 0
fi
IMAGE="${FHE_DEV_IMAGE:-ghcr.io/niobiuminc/fhe-dev:latest}"
FOG=(); [ -d "$HOME/.fog" ] && FOG=(-v "$HOME/.fog:/root/.fog")
exec docker run --rm -v "$PWD":/work -w /work "${FOG[@]}" "$IMAGE" bash -c "$*"
