#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
set -Eeuo pipefail

usage() {
  cat <<'EOF'
run_test.sh: encrypted polygenic risk scoring. keygen -> encrypt -> server
-> decrypt across a client home and a server home, then compare to the
faithful twin and the plaintext reference.

Usage: ./run_test.sh [--cpu | --sim | --sim-full] [-v] [-q] [-h]
  (no flag)   dispatch to the Niobium Fog (default; needs an API key). Records
              hollow (fast), the Fog reconstructs the real values on replay.
  --cpu       plain-OpenFHE local validation (the correctness gate)
  --sim       hollow record -> local fhetch_sim replay -> compare to the twin.
              A faithful local rehearsal of the (hollow) Fog run.
  --sim-full  real-math record -> replay, plus the ring-level ciphertext-identity
              check against the OpenFHE result (the thorough ground-truth run).
              Running --sim and --sim-full and comparing them surfaces any
              hollow-recording divergence.
  -v          pass the OpenFHE / Fog tool output through instead of logging it
              to run_<mode>/tools.log
  -q          suppress the stage table; keep the score report
  -h          this help

Streams: score report on stdout, stage table on stderr, tool output in
run_<mode>/tools.log.
Exit: 0 if the decrypted scores match the faithful twin within the Stage 7
tolerance with no high-risk reclassification, 1 if not, 2 on a usage error.

Env: FOG_TARGET (default FOG; FUNC_SIM = hardware-free functional simulator)
     RINGCHK   (set to --no-ring-dim-check only for a deliberately small ring;
                the design passes the check at N = 2^16)
     NREC      participants to score (batched in slabs of 32,768)
     NO_COLOR  disable colour (already off when stderr is not a TTY)
Run inside the FHE-dev container:  ./run-in-container.sh "./run_test.sh --cpu"
EOF
}

MODE="fog"; QUIET=0; VERBOSE=0
for arg in "$@"; do
  case "$arg" in
    --cpu) MODE="cpu";;
    --sim) MODE="sim";;
    --sim-full) MODE="sim-full";;
    -v|--verbose) VERBOSE=1;;
    -q|--quiet) QUIET=1;;
    -h|--help) usage; exit 0;;
    *) usage; exit 2;;
  esac
done

# ------------------------------------------------------------------ tty ----
# Score report on stdout, stage table on stderr, tool chatter in a log file, so
# `./run_test.sh --cpu > report.txt` captures the report whole. Colour only on
# an interactive stderr with NO_COLOR unset (https://no-color.org).
if [ -t 2 ] && [ -z "${NO_COLOR:-}" ] && [ "${TERM:-dumb}" != "dumb" ]; then
  TTY_ERR=1
  C_B=$'\033[1m'; C_DIM=$'\033[2m'; C_ERR=$'\033[31m'; C_OFF=$'\033[0m'
else
  TTY_ERR=0
  C_B=""; C_DIM=""; C_ERR=""; C_OFF=""
fi
RULE="========================================================================"
THIN="------------------------------------------------------------------------"

say()  { [ "$QUIET" = 1 ] || printf '%s\n' "$*" >&2; }
fact() { [ "$QUIET" = 1 ] || printf '%-16s%s\n' "$1" "$2" >&2; }
warn() { printf '%s\n' "$*" >&2; }
die()  { printf '%serror%s  %s\n' "$C_ERR" "$C_OFF" "$1" >&2
         [ $# -lt 2 ] || printf '%-7s%s\n' "fix" "$2" >&2
         exit "${3:-1}"; }

hsize() {  # bytes -> human
  awk -v b="$1" 'BEGIN{ split("B KiB MiB GiB TiB", u, " "); i = 1
    while (b >= 1024 && i < 5) { b /= 1024; i++ }
    printf (i == 1 ? "%d %s" : "%.1f %s"), b, u[i] }'
}
hnum() {  # 8000 -> 8,000
  awk -v n="$1" 'BEGIN{ s = sprintf("%d", n); out = ""
    while (length(s) > 3) { out = "," substr(s, length(s) - 2) out
                            s = substr(s, 1, length(s) - 3) }
    print s out }'
}
dirsize() { du -sb "$1" 2>/dev/null | cut -f1; }
stamp()   { date +%s.%N; }
elapsed() { echo "$1 $2" | awk '{printf "%.2f", $1-$2}'; }

# ---------------------------------------------------------- stage table ----
# One row per stage, written as it finishes. On a terminal the row opens with
# the stage name and a live elapsed counter, so a 30 s stage is not a blank
# screen; redirected to a file, only the finished rows are written.
STAGE=""; STAGE_T0=""; LAST_WALL=""; HB_PID=""; STAGE_PID=""; WATCH_DIR=""
ROW_FMT='%-10s %8s %10s %10s  %s\n'
[ "$TTY_ERR" = 1 ] && CLR=$'\r\033[K' || CLR=""

table_head() {
  [ "$QUIET" = 1 ] || printf "$ROW_FMT" stage wall "peak RSS" bytes output >&2
}

tree_rss() {  # KiB resident across pid $1 and its descendants
  ps -eo pid=,ppid=,rss= 2>/dev/null | awk -v root="$1" '
    { pid[n] = $1; ppid[$1] = $2; rss[$1] = $3; n++ }
    END { want[root] = 1
          for (pass = 0; pass < 6; pass++)
            for (i = 0; i < n; i++)
              if (want[ppid[pid[i]]]) want[pid[i]] = 1
          for (i = 0; i < n; i++) if (want[pid[i]]) total += rss[pid[i]]
          print total + 0 }'
}

# The heavy stages run 30 s or more. Sample them once a second so the terminal
# shows live memory and bytes rather than a frozen line. Redirected to a file,
# emit a whole line every 30 s instead of redrawing.
hb_start() {
  if [ "$QUIET" = 1 ]; then return 0; fi
  ( set +e
    t=0
    while :; do
      sleep 1; t=$((t + 1))
      mem=""; out=""
      if [ -n "$STAGE_PID" ]; then
        r=$(tree_rss "$STAGE_PID")
        if [ "${r:-0}" -gt 0 ]; then mem="   mem $(hsize $((r * 1024)))"; fi
      fi
      if [ -n "$WATCH_DIR" ] && [ -d "$WATCH_DIR" ]; then
        b=$(dirsize "$WATCH_DIR")
        if [ "${b:-0}" -gt 0 ]; then out="   out $(hsize "$b")"; fi
      fi
      if [ "$TTY_ERR" = 1 ]; then
        printf '%s%-10s %7ss%s%s%s' "$CLR" "$STAGE" "$t" "$C_DIM" "$mem$out" "$C_OFF" >&2
      elif [ $((t % 30)) -eq 0 ]; then
        printf '%-10s %7ss%s\n' "$STAGE" "$t" "$mem$out" >&2
      fi
    done ) &
  HB_PID=$!
}
hb_stop() {
  if [ -z "$HB_PID" ]; then return 0; fi
  kill "$HB_PID" 2>/dev/null || true
  wait "$HB_PID" 2>/dev/null || true
  HB_PID=""
}
begin() {  # begin <stage> [dir to watch for output bytes]
  STAGE="$1"; WATCH_DIR="${2:-}"; STAGE_PID=""; STAGE_T0=$(stamp)
  if [ "$QUIET" = 0 ] && [ "$TTY_ERR" = 1 ]; then printf '%-10s' "$STAGE" >&2; fi
}
end() {  # end <peak RSS> <bytes> <output>
  hb_stop
  LAST_WALL=$(elapsed "$(stamp)" "$STAGE_T0")
  STAGE_PID=""; WATCH_DIR=""
  if [ "$QUIET" = 1 ]; then return 0; fi
  printf '%s' "$CLR" >&2
  printf "$ROW_FMT" "$STAGE" "${LAST_WALL}s" "$1" "$2" "$3" >&2
}

# Run a tool in a home, backgrounded so the sampler can watch it. `exec` makes
# the binary itself the job, so $! is the pid whose tree we measure.
spawn() {  # spawn <dir> <cmd...>
  local d="$1"; shift
  if [ "$VERBOSE" = 1 ]; then ( cd "$d" && exec "$@" ) >&2 &
  else ( cd "$d" && exec "$@" ) >>"$TOOLLOG" 2>&1 & fi
  STAGE_PID=$!
  hb_start          # after the pid exists: the sampler forks with it in hand
}
await() { wait "$STAGE_PID"; }

FOG_TARGET="${FOG_TARGET:-FOG}"   # the real Niobium Fog; FUNC_SIM is the explicit hardware-free opt-in
RINGCHK="${RINGCHK:-}"
# Hollow recording (skip the real math on the record pass; the replay
# reconstructs the real values). The Fog default and --sim record hollow, so --sim is
# a faithful rehearsal of the Fog run; --sim-full records real math so its ring-level
# ciphertext-identity check has a real baseline; --cpu has no record pass.
case "$MODE" in fog|sim) HOLLOW=1;; *) HOLLOW=0;; esac
export HOLLOW
# The synthetic cohort is 8,000 participants (fits one 32,768-slot batch).
case "$MODE" in
  cpu) NREC="${NREC:-8000}";; sim|sim-full) NREC="${NREC:-8000}";; fog) NREC="${NREC:-8000}";;
esac
N_SLOTS=32768
N_BATCHES=$(( (NREC + N_SLOTS - 1) / N_SLOTS ))

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD="$ROOT/nb_out/build"
RUN="$ROOT/run_${MODE}"
CLIENT="$RUN/client_home"; SERVER="$RUN/server_home"
export LD_LIBRARY_PATH="/opt/niobium-client/vendor/lib/openfhe/lib:/opt/niobium-client/build/vendor/niobium-fhetch:/opt/niobium-client/vendor/niobium-fhetch/build:/opt/niobium-client/build/_deps/yaml_cpp-build${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export NBCC_FHETCH_SIM="${NBCC_FHETCH_SIM:-/opt/niobium-client/vendor/lib/niobium-client/bin/fhetch_sim}"
PROFILE="$RUN/profile.txt"
TOOLLOG="$RUN/tools.log"

on_err() {
  local rc=$?
  hb_stop
  [ "$TTY_ERR" = 0 ] || printf '\r' >&2
  printf '%s%s failed, exit %d%s\n' "$C_ERR" "${STAGE:-startup}" "$rc" "$C_OFF" >&2
  if [ -s "${TOOLLOG:-}" ]; then
    printf '%s:\n' "$TOOLLOG" >&2
    tail -n 15 "$TOOLLOG" | sed 's/^/  | /' >&2
  fi
  exit "$rc"
}
trap hb_stop EXIT
trap on_err ERR

N_MARKERS="$(awk 'NR==1{print NF; exit}' "$ROOT/data/input_batch_0.txt" 2>/dev/null || true)"
: "${N_MARKERS:=?}"

say ""
say "$RULE"
say "${C_B}polygenic risk scoring${C_OFF} (CKKS), mode $MODE"
say "$RULE"
fact "participants"   "$(hnum "$NREC")"
fact "markers"        "$(hnum "$N_MARKERS")"
fact "dosage"         "0, 1 or 2 risk alleles per marker"
fact "weights"        "$(hnum "$N_MARKERS") published effect sizes, plaintext, server-side"
fact "score"          "sum over markers of  dosage[marker] x weight[marker]"
fact "packing"        "column-major, $(hnum "$N_SLOTS") participants per ciphertext"
fact "batches"        "$N_BATCHES"
fact "ring"           "2^16 = 65,536"
fact "depth"          "1 multiplication, 0 rotations"
fact "client home"    "run_${MODE}/client_home   dosages, secret key, scores"
fact "server home"    "run_${MODE}/server_home   ciphertext, public keys, weights"
say "$THIN"

[ -x "$BUILD/keygen" ] || die "FHE binaries not built" \
  "./run-in-container.sh 'make build'"
[ -f "$ROOT/data/input_batch_0.txt" ] || die "no packed inputs in data/" \
  "./run-in-container.sh 'python3 harness/prepare_inputs.py'"
# The twin/reference comparison ledgers are generated by harness/validate_twin.py and are
# gitignored (regenerated, not committed). The correctness gate (harness/compare_results.py)
# reads them, so fail early with a clear pointer. validate_twin.py reads the gitignored
# genotypes.npy, so a fresh clone runs gen_data.py first.
for f in reference_scores.csv twin_scores.csv; do
  [ -f "$ROOT/data/$f" ] || die "data/$f missing" \
    "./run-in-container.sh 'python3 harness/gen_data.py && python3 harness/validate_twin.py'"
done

rm -rf "$RUN"; mkdir -p "$CLIENT/data" "$CLIENT/download" "$SERVER/keys" "$SERVER/model" "$SERVER/download"
cp "$ROOT"/data/input_batch_*.txt "$CLIENT/data/"
cp "$ROOT"/data/server_model/*.txt "$SERVER/model/"
: > "$TOOLLOG"

log_prof() { echo "$1 $2 $3 $4" >> "$PROFILE"; }  # stage batch wall rss_kb

table_head

# 1. keygen writes ALL keys into the client home
begin keygen "$CLIENT/keys"
spawn "$CLIENT" "$BUILD/keygen" 0
await
end - "$(hsize "$(dirsize "$CLIENT/keys")")" \
    "$(ls "$CLIENT"/keys/*.bin | wc -l) keys in client_home, incl. secret_key.bin"
log_prof keygen - "$LAST_WALL" -

# 2. provision the server home: context, public + eval keys, model. NO secret key,
#    NO plaintext inputs. This linear circuit needs no rotation keys, so copy
#    whatever public/eval keys keygen actually emitted (never the secret key).
begin provision
for f in "$CLIENT"/keys/*.bin; do
  b="$(basename "$f")"
  [ "$b" = "secret_key.bin" ] && continue
  cp "$f" "$SERVER/keys/"
done
[ ! -f "$SERVER/keys/secret_key.bin" ] || die "secret key reached the server home"
end - "$(hsize "$(dirsize "$SERVER")")" \
    "$(ls "$SERVER"/keys/*.bin | wc -l) keys + weights.txt to server_home, no secret_key.bin"

# 3. negative test: the server must refuse to start with a secret key in its home
begin guard
cp "$CLIENT/keys/secret_key.bin" "$SERVER/keys/secret_key.bin"
if ( cd "$SERVER" && "$ROOT/server_guard.sh" "$BUILD/score" 0 0 $RINGCHK >/dev/null 2>&1 ); then
  die "server ran with secret_key.bin present in its home"
fi
rm -f "$SERVER/keys/secret_key.bin"
end - - "secret_key.bin planted in server_home, server exited 13"

# 4. Fog mode: preflight for an API key; with a key present, the dispatch below is mandatory
if [ "$MODE" = "fog" ] && [ ! -f "$HOME/.fog/credentials" ] && [ ! -f /root/.fog/credentials ] && [ -z "${FOG_API_TOKEN:-}" ]; then
  warn ""
  warn "mode fog needs a Niobium Fog API key; none found."
  warn "  sign in     fog login"
  warn "  sign up     https://console.niobium.co/request-account"
  warn "  no account  ./run_test.sh --sim"
  exit 0
fi

# The server pass, timed with its peak child RSS — the number a provider sizes
# RAM against.
read -r -d '' SERVER_RUNNER <<'PYEOF' || true
import os, resource, subprocess, sys, time
root, build, k, label, profile, ringchk = sys.argv[1:7]
cmd = [f"{root}/server_guard.sh", f"{build}/score", "0", k]
if ringchk:
    cmd.append(ringchk)
if os.environ.get("HOLLOW") == "1" and label.endswith("_record"):
    cmd.append("--hollow")   # hollow only on the record pass; replay reconstructs real values
t0 = time.time()
p = subprocess.run(cmd)
wall = time.time() - t0
rss = resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss  # KiB on Linux
with open(profile, "a") as fh:
    fh.write(f"{label} {k} {wall:.2f} {rss}\n")
sys.exit(p.returncode)
PYEOF

run_server_profiled() {  # $1 = batch id, $2 = label for profile
  spawn "$SERVER" python3 -c "$SERVER_RUNNER" \
    "$ROOT" "$BUILD" "$1" "$2" "$PROFILE" "$RINGCHK"
  await
}
server_rss() {  # peak RSS from the profile row run_server_profiled just appended
  awk 'END{ if ($4 == "-") print "-"; else printf "%.2f GiB", $4 / 1048576 }' "$PROFILE"
}
traced_ops() {  # ring-level instruction count, when the tracer reported one
  sed -n 's/.*(\([0-9][0-9]*\) instructions.*/\1/p' "$TOOLLOG" 2>/dev/null | tail -n 1
}

# 5. per slot-batch: encrypt -> (only ciphertext crosses) -> server -> decrypt
for ((k=0; k<N_BATCHES; k++)); do
  begin encrypt "$CLIENT/upload"
  spawn "$CLIENT" "$BUILD/encrypt" 0 "$k"   # bounds already enforced by harness/prepare_inputs.py
  await
  mkdir -p "$SERVER/upload/batch_$k"
  mv "$CLIENT"/upload/markers_*.bin "$SERVER/upload/batch_$k/"
  end - "$(hsize "$(dirsize "$SERVER/upload/batch_$k")")" \
      "batch $k: $(hnum "$N_MARKERS") marker ciphertexts -> server_home"
  log_prof encrypt "$k" "$LAST_WALL" -

  rm -rf "$SERVER"/score_profile_*_batch_id_"$k"     # force a fresh record for this batch
  case "$MODE" in
    cpu)
      begin score "$SERVER/download"
      run_server_profiled "$k" server_cpu
      end "$(server_rss)" - \
          "$(hnum "$N_MARKERS") ct x pt multiplies, $(hnum "$((N_MARKERS - 1))") adds -> 1 ciphertext"
      ;;
    sim|sim-full)
      # --sim records hollow (HOLLOW=1, set above) — a rehearsal of the Fog run,
      # gated on the twin. --sim-full records real math and additionally runs the
      # ring-level ciphertext-identity check (which needs a real record-pass baseline).
      begin record "$SERVER/download"
      run_server_profiled "$k" server_record
      TRACED="$(traced_ops)"
      end "$(server_rss)" - "batch $k trace${TRACED:+: $(hnum "$TRACED") ring ops}"
      if [ "$MODE" = "sim-full" ]; then
        cp "$SERVER/download/cipher_scores_$k.bin" "$SERVER/download/cipher_scores_$k.openfhe.bin"
      fi
      begin replay "$SERVER/download"
      run_server_profiled "$k" server_sim_replay    # cache-valid -> fhetch_sim reconstructs
      end "$(server_rss)" - "fhetch_sim replay -> 1 ciphertext"
      if [ "$MODE" = "sim-full" ]; then
        begin identity
        if cmp -s "$SERVER/download/cipher_scores_$k.bin" "$SERVER/download/cipher_scores_$k.openfhe.bin"; then
          end - - "simulator vs OpenFHE ciphertext: bit-identical"
        else
          end - - "simulator vs OpenFHE ciphertext: differ, decoded delta in (c)"
        fi
      fi
      ;;
    fog)
      begin record "$SERVER/download"
      run_server_profiled "$k" server_record        # write the trace (also yields the OpenFHE baseline)
      TRACED="$(traced_ops)"
      end "$(server_rss)" - "batch $k trace${TRACED:+: $(hnum "$TRACED") ring ops}"
      cp "$SERVER/download/cipher_scores_$k.bin" "$SERVER/download/cipher_scores_$k.openfhe.bin"
      # THE DEFAULT PATH: the server runs under `fog submit` (cache-valid ->
      # replay dispatches to the Fog worker). A default mode that preflights
      # and exits without ever calling `fog submit` is incomplete.
      begin dispatch "$SERVER/download"
      # The Fog runs exactly N=2^16, so the ring-dim guard stays on here (RINGCHK, the local-testing bypass, is not forwarded).
      spawn "$SERVER" fog submit "$BUILD/score" --target="$FOG_TARGET" 0 "$k"
      await
      end - - "batch $k -> Fog ($FOG_TARGET) -> 1 ciphertext"
      log_prof server_fog "$k" "$LAST_WALL" -
      ;;
  esac

  cp "$SERVER/download/cipher_scores_$k.bin" "$CLIENT/download/"
  DOWN_B=$(stat -c%s "$SERVER/download/cipher_scores_$k.bin")
  begin decrypt
  spawn "$CLIENT" "$BUILD/decrypt" 0 "$k"
  await
  end - "$(hsize "$DOWN_B")" "1 ciphertext <- server_home -> $(hnum "$NREC") scores"
  log_prof decrypt "$k" "$LAST_WALL" -
done

# 6. boundary sizes into the profile
{
  echo "== boundary sizes (bytes) =="
  for f in "$SERVER"/keys/*.bin; do echo "key $(basename "$f") $(stat -c%s "$f")"; done
  for ((k=0; k<N_BATCHES; k++)); do
    up=$(du -bc "$SERVER/upload/batch_$k"/markers_*.bin | tail -1 | cut -f1)
    down=$(stat -c%s "$SERVER/download/cipher_scores_$k.bin")
    echo "upload batch_$k $up"; echo "download batch_$k $down"
  done
} >> "$PROFILE"

say "$THIN"

# 7. report: (a) the decrypted scores; (b) quality vs ground truth; (c) FHE vs
#    twin against the Stage 7 tolerance (the PASS/FAIL exit code); (d) profile.
#    compare_results.py's non-zero exit is a verdict, not a crash.
trap - ERR
python3 "$ROOT/harness/compare_results.py" "$RUN" "$NREC" "$MODE"
