#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
# Trust-boundary guard: refuse to launch the server if a secret key is
# present in the server home (the current directory). The DSL already makes
# secret-key access a compile error in @server code; this runtime guard is
# the check a reviewer can exercise (plant a key, watch the refusal).
if [ -f keys/secret_key.bin ] || [ -f secret_key.bin ] || [ -f keys/sk.bin ] || [ -f sk.bin ]; then
  echo "[server-guard] REFUSING to start: a secret key is present in the server home" >&2
  exit 13
fi
exec "$@"
