# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
"""
Two-process client/server demo (the deployment-shaped run).

Client and server run as SEPARATE OS processes communicating only over HTTP,
exchanging serialized ciphertext — never keys-that-decrypt, never plaintext.

  server process (run_demo/server_home) — the outside compute provider:
    - REFUSES to start if a secret key is present in its home
    - setup endpoint receives context + public/eval keys + the public weights
    - runs the generated `score` binary on the encrypted batch
    - logs ONLY byte counts — it never sees (and cannot see) a genotype or score
  client process (run_demo/client_home) — the biobank:
    - generates all keys; the secret key NEVER crosses the wire
    - imputes / clips the dosages (prepare_inputs.py output), encrypts,
      uploads, downloads, decrypts, prints scores

Point the client at a remote host with SERVER_URL=http://host:port — the
server home is safe to copy to an untrusted machine as-is.

Usage (inside the container):  python3 harness/demo_two_process.py
"""

import http.server
import json
import os
import shutil
import subprocess
import sys
import threading
import time
import urllib.request

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "nb_out", "build")
RUN = os.path.join(ROOT, "run_demo")
CLIENT = os.path.join(RUN, "client_home")
SERVER = os.path.join(RUN, "server_home")
PORT = int(os.environ.get("DEMO_PORT", "8471"))
SERVER_URL = os.environ.get("SERVER_URL", f"http://127.0.0.1:{PORT}")
BATCH = 0  # the demo scores slot-batch 0 (the whole synthetic cohort)

LD = ("/opt/niobium-client/vendor/lib/openfhe/lib:"
      "/opt/niobium-client/build/vendor/niobium-fhetch:"
      "/opt/niobium-client/vendor/niobium-fhetch/build:"
      "/opt/niobium-client/build/_deps/yaml_cpp-build")


def run(cmd, cwd):
    env = dict(os.environ, LD_LIBRARY_PATH=LD)
    subprocess.run(cmd, cwd=cwd, env=env, check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


# ---------------------------------------------------------------- server ---
class ServerHandler(http.server.BaseHTTPRequestHandler):
    """The untrusted compute provider. Sees bytes in, bytes out."""

    def log_message(self, fmt, *args):  # quiet the default access log
        pass

    def do_PUT(self):
        # receive a file into the server home (setup keys / input ciphertext)
        rel = self.path.lstrip("/")
        dest = os.path.normpath(os.path.join(SERVER, rel))
        assert dest.startswith(SERVER), "path escape"
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        n = int(self.headers["Content-Length"])
        with open(dest, "wb") as fh:
            remaining = n
            while remaining:
                chunk = self.rfile.read(min(1 << 20, remaining))
                fh.write(chunk)
                remaining -= len(chunk)
        print(f"[server] received {n:>12,} bytes -> {rel}  (opaque to me)")
        self.send_response(200)
        self.end_headers()

    def do_POST(self):
        # /score/<batch> — run the encrypted computation
        batch = self.path.rsplit("/", 1)[-1]
        t0 = time.time()
        run([os.path.join(ROOT, "server_guard.sh"),
             os.path.join(BUILD, "score"), "0", batch], cwd=SERVER)
        dt = time.time() - t0
        out = os.path.join(SERVER, "download", f"cipher_scores_{batch}.bin")
        data = open(out, "rb").read()
        print(f"[server] scored batch {batch} in {dt:.1f}s; returning "
              f"{len(data):,} bytes, still encrypted — I never saw a "
              f"genotype or a score")
        self.send_response(200)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)


def start_server():
    # The runtime trust guard: refuse to serve if a secret key is present.
    for p in ("keys/secret_key.bin", "secret_key.bin"):
        if os.path.exists(os.path.join(SERVER, p)):
            print("[server] REFUSING to start: secret key found in server "
                  "home", file=sys.stderr)
            sys.exit(13)
    httpd = http.server.HTTPServer(("127.0.0.1", PORT), ServerHandler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    print(f"[server] compute provider listening on {SERVER_URL} "
          f"(home: {SERVER})")
    return httpd


# ---------------------------------------------------------------- client ---
def put(rel, path):
    with open(path, "rb") as fh:
        data = fh.read()
    req = urllib.request.Request(f"{SERVER_URL}/{rel}", data=data,
                                 method="PUT")
    urllib.request.urlopen(req).read()


def client_flow():
    print("[client] generating keys (secret key stays in my home)")
    run([os.path.join(BUILD, "keygen"), "0"], cwd=CLIENT)

    print("[client] SETUP upload: context + public/eval keys + public weights "
          "(no secret key crosses the wire)")
    for f in sorted(os.listdir(os.path.join(CLIENT, "keys"))):
        if f == "secret_key.bin":
            continue
        put(f"keys/{f}", os.path.join(CLIENT, "keys", f))
    for f in os.listdir(os.path.join(ROOT, "data", "server_model")):
        put(f"model/{f}", os.path.join(ROOT, "data", "server_model", f))

    print("[client] encrypting batch 0 (dosages pre-imputed + clipped to "
          "[0,2] by prepare_inputs.py)")
    run([os.path.join(BUILD, "encrypt"), "0", str(BATCH)], cwd=CLIENT)
    updir = os.path.join(CLIENT, "upload")
    for f in sorted(os.listdir(updir)):
        put(f"upload/batch_{BATCH}/{f}", os.path.join(updir, f))

    print("[client] requesting encrypted scoring")
    req = urllib.request.Request(f"{SERVER_URL}/score/{BATCH}",
                                 method="POST")
    data = urllib.request.urlopen(req, timeout=1200).read()
    os.makedirs(os.path.join(CLIENT, "download"), exist_ok=True)
    with open(os.path.join(CLIENT, "download",
                           f"cipher_scores_{BATCH}.bin"), "wb") as fh:
        fh.write(data)
    print(f"[client] received {len(data):,} encrypted bytes; decrypting "
          f"with MY secret key")
    run([os.path.join(BUILD, "decrypt"), "0", str(BATCH)], cwd=CLIENT)

    raw = np.fromfile(os.path.join(CLIENT, f"scores_batch_{BATCH}.bin"))
    meta = json.load(open(os.path.join(ROOT, "data", "batches_meta.json")))
    n_valid = meta["n_valid"][BATCH]
    scores = raw[:n_valid]
    twin = []
    import csv as _csv
    with open(os.path.join(ROOT, "data", "twin_scores.csv")) as fh:
        r = _csv.reader(fh)
        next(r)
        for row in r:
            twin.append(float(row[1]))
    twin = np.array(twin)[:n_valid]
    print(f"[client] first 5 participants' risk scores: "
          f"{[round(float(s), 4) for s in scores[:5]]}")
    print(f"[client] agreement with the faithful twin: max "
          f"|delta| {np.max(np.abs(scores - twin)):.3e} over "
          f"{len(scores)} participants")


def main():
    # provision the two homes
    shutil.rmtree(RUN, ignore_errors=True)
    os.makedirs(os.path.join(CLIENT, "data"))
    os.makedirs(os.path.join(CLIENT, "download"))
    os.makedirs(os.path.join(SERVER, "download"))
    shutil.copy(os.path.join(ROOT, "data", f"input_batch_{BATCH}.txt"),
                os.path.join(CLIENT, "data"))

    print("=" * 72)
    print("Two-process demo: biobank client and untrusted compute provider, "
          "ciphertext-only wire")
    print("=" * 72)

    # negative test first: plant a secret key, prove the server refuses
    os.makedirs(os.path.join(SERVER, "keys"), exist_ok=True)
    plant = os.path.join(SERVER, "keys", "secret_key.bin")
    open(plant, "wb").write(b"planted")
    r = subprocess.run([sys.executable, __file__, "--server-only"],
                       capture_output=True, text=True)
    assert r.returncode == 13, "server must refuse a planted secret key"
    print("[demo] negative test: server refused to start with a planted "
          "secret key (exit 13)")
    os.remove(plant)

    start_server()
    time.sleep(0.3)
    client_flow()
    print("[demo] done. The provider handled only ciphertext throughout.")


if __name__ == "__main__":
    if "--server-only" in sys.argv:
        # used by the negative test: start (and refuse) without a client
        for p in ("keys/secret_key.bin", "secret_key.bin"):
            if os.path.exists(os.path.join(SERVER, p)):
                print("[server] REFUSING to start: secret key found in "
                      "server home", file=sys.stderr)
                sys.exit(13)
        sys.exit(0)
    main()
