# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
"""
gen_data.py — synthesize a SYNTHETIC genomics cohort for the encrypted
polygenic-risk-scoring demo.

Real participant genotypes are exactly the sensitive data this application
exists to protect, so we cannot ship any here. Instead we generate an
independent, principled synthetic cohort using the standard **liability-
threshold model** from statistical genetics (Falconer; Wray et al. 2010,
"The genetic interpretation of area under the ROC curve in genomic profiling").
Swap in your real dosage matrix + published weights later — nothing downstream
depends on the data being synthetic.

Generative model (all markers unlinked, Hardy-Weinberg):
  1. Each marker m gets a minor-allele frequency  maf_m ~ U(0.05, 0.5).
  2. Genotype dosage           g[p,m] ~ Binomial(2, maf_m)          in {0,1,2}.
  3. A fraction of markers are truly causal with standardized effect a_m;
     genetic liability  G_p = sum_m z[p,m] a_m  (z = standardized genotype),
     scaled so Var(G) = h2 (liability-scale heritability).
  4. Liability  L_p = G_p + E_p,  E_p ~ N(0, 1-h2);  a participant is a CASE
     (phenotype = 1) iff L_p exceeds the threshold for disease prevalence K.
  5. PUBLISHED per-allele weights  w_m = beta_true_m + GWAS estimation noise.
     The PRS uses these public weights on the RAW dosages, exactly as
     PLINK `--score` does:   prs[p] = sum_m g[p,m] * w_m.

Note the labels (phenotype) are drawn from an INDEPENDENT latent liability,
never from the PRS itself — so PRS-vs-phenotype AUC is an honest measure of
how well the score stratifies risk, not a self-fulfilling tautology.

Outputs (in data/):
  genotypes.npy      int8  [n_participants, n_markers]  — the sensitive dosages
  weights.csv        marker_id, maf, beta_true, weight  — public effect weights
  labels.csv         participant_id, prs_true, liability, phenotype
  marker_bounds.csv  marker_id, lo, hi                  — input box [0, 2]
  gen_meta.json      generation parameters + realized statistics
"""

import csv
import json
import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")

# ---- generation parameters (deterministic) --------------------------------
SEED = 20260803
N_MARKERS = 2000          # markers per participant ("a few thousand")
N_PARTICIPANTS = 8000     # study cohort (fits one 32,768-slot batch)
MAF_LO, MAF_HI = 0.05, 0.50
CAUSAL_FRAC = 0.50        # fraction of panel markers with a true effect
H2 = 0.50                 # liability-scale heritability
PREVALENCE = 0.10         # disease base rate (10% cases)
NOISE_FRAC = 0.75         # GWAS estimation noise, as a fraction of the typical
                          # causal per-allele effect (tuned for a realistic AUC)
DOSAGE_LO, DOSAGE_HI = 0.0, 2.0


def norm_ppf(q):
    """Inverse standard-normal CDF (rational approximation, Acklam)."""
    from math import sqrt, log
    a = [-3.969683028665376e+01, 2.209460984245205e+02, -2.759285104469687e+02,
         1.383577518672690e+02, -3.066479806614716e+01, 2.506628277459239e+00]
    b = [-5.447609879822406e+01, 1.615858368580409e+02, -1.556989798598866e+02,
         6.680131188771972e+01, -1.328068155288572e+01]
    c = [-7.784894002430293e-03, -3.223964580411365e-01, -2.400758277161838e+00,
         -2.549732539343734e+00, 4.374664141464968e+00, 2.938163982698783e+00]
    d = [7.784695709041462e-03, 3.224671290700398e-01, 2.445134137142996e+00,
         3.754408661907416e+00]
    plow, phigh = 0.02425, 1 - 0.02425
    if q < plow:
        r = sqrt(-2 * log(q))
        return (((((c[0]*r+c[1])*r+c[2])*r+c[3])*r+c[4])*r+c[5]) / \
               ((((d[0]*r+d[1])*r+d[2])*r+d[3])*r+1)
    if q > phigh:
        r = sqrt(-2 * log(1 - q))
        return -(((((c[0]*r+c[1])*r+c[2])*r+c[3])*r+c[4])*r+c[5]) / \
                ((((d[0]*r+d[1])*r+d[2])*r+d[3])*r+1)
    r = q - 0.5
    s = r * r
    return (((((a[0]*s+a[1])*s+a[2])*s+a[3])*s+a[4])*s+a[5])*r / \
           (((((b[0]*s+b[1])*s+b[2])*s+b[3])*s+b[4])*s+1)


def main():
    os.makedirs(DATA, exist_ok=True)
    rng = np.random.default_rng(SEED)

    # 1. allele frequencies
    maf = rng.uniform(MAF_LO, MAF_HI, N_MARKERS)

    # 2. genotype dosages under Hardy-Weinberg
    genotypes = rng.binomial(2, maf, size=(N_PARTICIPANTS, N_MARKERS)).astype(np.int8)

    # 3. true standardized effects on the causal subset, scaled to heritability H2
    causal = rng.random(N_MARKERS) < CAUSAL_FRAC
    a = np.zeros(N_MARKERS)
    a[causal] = rng.normal(0.0, 1.0, int(causal.sum()))
    sd_geno = np.sqrt(2.0 * maf * (1.0 - maf))          # per-marker genotype SD
    z = (genotypes - 2.0 * maf) / sd_geno               # standardized genotypes
    Graw = z @ a
    scale = np.sqrt(H2 / Graw.var())
    G = Graw * scale                                    # genetic liability, Var = H2
    a_scaled = a * scale
    beta_true = a_scaled / sd_geno                      # per-allele effect on raw dosage

    E = rng.normal(0.0, np.sqrt(1.0 - H2), N_PARTICIPANTS)
    liability = G + E                                   # Var ~ 1
    liability = (liability - liability.mean()) / liability.std()

    # 4. phenotype by liability threshold for the target prevalence
    tau = norm_ppf(1.0 - PREVALENCE)
    phenotype = (liability > tau).astype(int)

    # 5. published weights = true effect + homoscedastic GWAS estimation noise
    #    (noise scaled to the typical causal per-allele effect size)
    sig = beta_true[causal].std()
    weight = beta_true + rng.normal(0.0, NOISE_FRAC * sig, N_MARKERS)

    # reference PRS with the PUBLISHED weights (what the server will compute)
    prs_true = genotypes.astype(np.float64) @ weight

    # ---- write artifacts --------------------------------------------------
    np.save(os.path.join(DATA, "genotypes.npy"), genotypes)

    with open(os.path.join(DATA, "weights.csv"), "w", newline="") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["marker_id", "maf", "beta_true", "weight"])
        for m in range(N_MARKERS):
            w.writerow([m, f"{maf[m]:.6f}", f"{beta_true[m]:.8g}", f"{weight[m]:.8g}"])

    with open(os.path.join(DATA, "labels.csv"), "w", newline="") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["participant_id", "prs_true", "liability", "phenotype"])
        for p in range(N_PARTICIPANTS):
            w.writerow([p, f"{prs_true[p]:.10g}", f"{liability[p]:.6g}", phenotype[p]])

    with open(os.path.join(DATA, "marker_bounds.csv"), "w", newline="") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["marker_id", "lo", "hi"])
        for m in range(N_MARKERS):
            w.writerow([m, DOSAGE_LO, DOSAGE_HI])

    # realized diagnostics
    from math import erf, sqrt
    ps = (prs_true - prs_true.mean()) / prs_true.std()
    order = np.argsort(ps)[::-1]
    k10 = max(1, int(0.10 * N_PARTICIPANTS))
    top10_case_rate = phenotype[order[:k10]].mean()
    meta = {
        "seed": SEED, "n_markers": N_MARKERS, "n_participants": N_PARTICIPANTS,
        "maf_range": [MAF_LO, MAF_HI], "causal_frac": CAUSAL_FRAC,
        "n_causal": int(causal.sum()), "h2": H2, "prevalence": PREVALENCE,
        "noise_frac": NOISE_FRAC, "dosage_box": [DOSAGE_LO, DOSAGE_HI],
        "realized_prevalence": float(phenotype.mean()),
        "prs_mean": float(prs_true.mean()), "prs_std": float(prs_true.std()),
        "prs_min": float(prs_true.min()), "prs_max": float(prs_true.max()),
        "top_decile_case_rate": float(top10_case_rate),
        "synthetic": True,
        "generative_model": "liability-threshold (Wray et al. 2010)",
    }
    with open(os.path.join(DATA, "gen_meta.json"), "w") as fh:
        json.dump(meta, fh, indent=2)

    print(f"[gen_data] {N_PARTICIPANTS} participants x {N_MARKERS} markers "
          f"({int(causal.sum())} causal)")
    print(f"[gen_data] realized prevalence = {phenotype.mean():.3f} "
          f"(target {PREVALENCE})")
    print(f"[gen_data] raw PRS range = [{prs_true.min():.3f}, {prs_true.max():.3f}], "
          f"mean {prs_true.mean():.3f}, sd {prs_true.std():.3f}")
    print(f"[gen_data] top-decile case rate = {top10_case_rate:.3f} "
          f"(vs base rate {phenotype.mean():.3f})")


if __name__ == "__main__":
    main()
