# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
"""
Client-side input preparation (runs in the clear, on the client).

For this linear circuit the client-side steps are genotype data hygiene, not
decode-safety enforcement (a weighted sum has no polynomial domain to overrun):

  1. read the cohort's dosage matrix (genotypes.npy) and the committed input
     box (marker_bounds.csv = [0, 2] per marker)
  2. IMPUTE missing calls (a negative sentinel) to the marker's mean dosage
     2*maf — the standard PRS treatment of a no-call
  3. CLIP every dosage into [0, 2] (guards against corrupt / mis-scaled input)
  4. zero-pad to whole 32,768-slot batches (a padding row scores 0) and write
     one space-separated text matrix per batch for the encrypt binary, packed
     column-major (participants across rows, markers across columns)
  5. export the PUBLIC per-marker weights the server home is provisioned with

Outputs:
  data/input_batch_<k>.txt   n_slots x n_markers, imputed + clipped dosages
  data/batches_meta.json     n_valid per batch
  data/server_model/weights.txt   n_markers x 1 (public effect weights)
"""

import json
import os

import numpy as np

import refmodel as rm

N_SLOTS = 32768


def pack_batches(G):
    """Split the participants x markers dosage matrix into 32,768-row batches,
    zero-padding the final batch. Returns [(matrix, n_valid), ...]."""
    n, m = G.shape
    batches = []
    for start in range(0, max(n, 1), N_SLOTS):
        chunk = G[start:start + N_SLOTS]
        n_valid = chunk.shape[0]
        if n_valid < N_SLOTS:
            pad = np.zeros((N_SLOTS - n_valid, m), dtype=np.float64)
            chunk = np.vstack([chunk, pad])
        batches.append((chunk, n_valid))
    return batches


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ddir = os.path.join(here, "..", "data")

    G = rm.load_genotypes(os.path.join(ddir, "genotypes.npy"))
    W = rm.load_weights(os.path.join(ddir, "weights.csv"))
    lo, hi = rm.load_bounds(os.path.join(ddir, "marker_bounds.csv"))

    # impute no-calls (negative sentinel) to mean dosage, then clip — client_clear
    maf = W["maf"]
    missing = G < 0
    if missing.any():
        mean_dosage = np.broadcast_to(2.0 * maf, G.shape)
        G = np.where(missing, mean_dosage, G)
    Gc = rm.clip_dosages(G, lo, hi)

    batches = pack_batches(Gc)
    meta = {"n_slots": N_SLOTS, "n_batches": len(batches),
            "n_valid": [int(n) for _, n in batches],
            "genotypes_file": "genotypes.npy"}
    for k, (Gb, _) in enumerate(batches):
        np.savetxt(os.path.join(ddir, f"input_batch_{k}.txt"), Gb,
                   fmt="%.6g", delimiter=" ")
    with open(os.path.join(ddir, "batches_meta.json"), "w") as fh:
        json.dump(meta, fh, indent=2)

    # public per-marker weights for the server home (n_markers x 1)
    mdir = os.path.join(ddir, "server_model")
    os.makedirs(mdir, exist_ok=True)
    np.savetxt(os.path.join(mdir, "weights.txt"), W["weight"][:, None],
               fmt="%.17g", delimiter=" ")

    n_missing = int(missing.sum())
    n_clipped = int(np.count_nonzero(Gc != G))
    n_pad = sum(N_SLOTS - n for _, n in batches)

    def row(label, value, detail=""):
        print(f"{label:<18}{value:>9}  {detail}".rstrip())

    row("participants", f"{G.shape[0]:,}")
    row("markers", f"{G.shape[1]:,}")
    row("no-calls imputed", f"{n_missing:,}", "to the marker mean dosage 2*maf")
    row("dosages clipped", f"{n_clipped:,}",
        f"into [{lo.min():g}, {hi.max():g}]")
    row("batches", f"{len(batches):,}",
        f"{N_SLOTS:,} slots each, {n_pad:,} padding rows scoring 0")
    row("public weights", f"{G.shape[1]:,}", "plaintext, provisioned to the server")
    print("written")
    for rel in ([f"input_batch_{k}.txt" for k in range(len(batches))]
                + ["batches_meta.json", "server_model/weights.txt"]):
        nbytes = os.path.getsize(os.path.join(ddir, rel))
        for unit in ("B", "KiB", "MiB", "GiB"):
            if nbytes < 1024 or unit == "GiB":
                break
            nbytes /= 1024
        size = f"{nbytes:.0f} {unit}" if unit == "B" else f"{nbytes:.1f} {unit}"
        print(f"  data/{rel:<40}{size:>10}")


if __name__ == "__main__":
    main()
