# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
"""
refmodel.py — the plaintext REFERENCE for encrypted polygenic risk scoring.

The reference computation is the canonical polygenic-risk-score (PRS) formula,
identical to what tools such as PLINK `--score` or the PGS Catalog calculator
produce:

    score[p] = sum_m  dosage[p, m] * weight[m]

  * dosage[p, m]  — participant p's genotype at marker m, a count of risk
                    alleles in {0, 1, 2} (or an imputed value in [0, 2]).
  * weight[m]     — the marker's published per-allele effect weight (a public
                    number from a genome-wide association study).

This module is the single shared plaintext pipeline used by every other stage
(twin, validation, input prep, result comparison). It has no dependency on any
FHE machinery — it is the ground truth everything else is measured against.
"""

import csv
import json
import numpy as np


# ------------------------------------------------------------------ I/O ----

def load_genotypes(path):
    """Load the raw dosage matrix (participants x markers), as float64."""
    return np.load(path).astype(np.float64)


def load_weights(path):
    """Load data/weights.csv -> dict of column arrays keyed by header name."""
    rows = []
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            rows.append(row)
    marker_id = np.array([int(r["marker_id"]) for r in rows])
    maf = np.array([float(r["maf"]) for r in rows])
    beta_true = np.array([float(r["beta_true"]) for r in rows])
    weight = np.array([float(r["weight"]) for r in rows])
    return {"marker_id": marker_id, "maf": maf, "beta_true": beta_true,
            "weight": weight}


def load_bounds(path):
    """Load data/marker_bounds.csv -> (lo[m], hi[m]) per-marker input box."""
    lo, hi = [], []
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            lo.append(float(row["lo"]))
            hi.append(float(row["hi"]))
    return np.array(lo), np.array(hi)


def load_labels(path):
    """Load data/labels.csv -> dict of column arrays."""
    rows = []
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            rows.append(row)
    return {
        "participant_id": np.array([int(r["participant_id"]) for r in rows]),
        "prs_true": np.array([float(r["prs_true"]) for r in rows]),
        "liability": np.array([float(r["liability"]) for r in rows]),
        "phenotype": np.array([int(r["phenotype"]) for r in rows]),
    }


def load_meta(path):
    with open(path) as fh:
        return json.load(fh)


# ------------------------------------------------------------- scoring ----

def clip_dosages(genotypes, lo, hi):
    """Client-side data hygiene: clip each marker's dosage into its [lo, hi]
    box. For a linear model this cannot cause an out-of-domain divergence
    (there is no polynomial to overrun); it only guards against corrupt or
    mis-scaled input. Missing values should already be imputed upstream."""
    return np.clip(genotypes, lo, hi)


def reference_scores(genotypes, weight):
    """The reference PRS: a plain weighted sum, in exact float64 arithmetic."""
    return genotypes @ weight


# --------------------------------------------------------- task metrics ----

def roc_auc(scores, labels):
    """ROC AUC via the Mann-Whitney U statistic (no sklearn dependency).
    Measures how well the score ranks cases above controls."""
    labels = np.asarray(labels)
    order = np.argsort(scores, kind="mergesort")
    ranks = np.empty(len(scores), dtype=np.float64)
    ranks[order] = np.arange(1, len(scores) + 1)
    # average ranks for ties
    s = np.asarray(scores)
    _, inv, counts = np.unique(s, return_inverse=True, return_counts=True)
    csum = np.cumsum(counts)
    start = csum - counts
    avg = (start + csum + 1) / 2.0
    ranks = avg[inv]
    n_pos = int(labels.sum())
    n_neg = len(labels) - n_pos
    if n_pos == 0 or n_neg == 0:
        return float("nan")
    sum_pos = ranks[labels == 1].sum()
    return (sum_pos - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg)


def top_fraction_flags(scores, frac):
    """Boolean mask of the highest-scoring `frac` of participants — the
    'high genetic risk' bucket a biobank would flag for follow-up."""
    n = len(scores)
    k = max(1, int(round(frac * n)))
    thresh_idx = np.argsort(scores, kind="mergesort")[::-1][:k]
    mask = np.zeros(n, dtype=bool)
    mask[thresh_idx] = True
    return mask


def spearman(a, b):
    """Spearman rank correlation between two score vectors."""
    def rank(x):
        order = np.argsort(x, kind="mergesort")
        r = np.empty(len(x), dtype=np.float64)
        r[order] = np.arange(len(x))
        return r
    ra, rb = rank(a), rank(b)
    ra -= ra.mean(); rb -= rb.mean()
    denom = np.sqrt((ra * ra).sum() * (rb * rb).sum())
    return float((ra * rb).sum() / denom) if denom > 0 else float("nan")
