# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
"""
twin.py — the FAITHFUL TWIN of the encrypted polygenic-risk-scoring circuit.

The twin is a plaintext (numpy) model of the *exact* homomorphic circuit the
server will run, so it predicts the encrypted behaviour up to random encryption
noise. Concretely it reproduces:

  * column-major SIMD packing — one ciphertext per marker, participants across
    the 32,768 slots (zero-padded);
  * fixed-point quantization to the CKKS grid (Delta = 2^scaling) at every
    operation, matching the rescale after each cipher x plaintext multiply;
  * the same multiply-accumulate:  score[p] = sum_m  g[p,m] * w[m].

Because the circuit is a single depth-1 weighted sum (one multiply per marker,
then free additions), the quantization error is ~2^-scaling relative and the
twin tracks the reference to full double precision. There is no polynomial
approximation and hence no approximation error — the only gap the twin models
is the fixed-point grid; the only gap left for the encrypted run is CKKS noise.
"""

import numpy as np

N_SLOTS = 32768           # CKKS slots at ring dimension 2^16 (N/2)
SCALING = 45              # bits per level (Delta = 2^SCALING)
FIRST_MOD = 60            # first-modulus bits
DEPTH = 2                 # multiplicative depth (1 used + 1 spare)
LEVELS_USED = 1           # one cipher x plaintext multiply on the critical path


def quantize(x, scaling=SCALING):
    """Round to the CKKS fixed-point grid with step 2^-scaling."""
    delta = float(1 << scaling)
    return np.round(np.asarray(x, dtype=np.float64) * delta) / delta


def pack_columns(genotypes, n_slots=N_SLOTS):
    """Column-major pack: return a list of length n_markers, each a length
    n_slots vector holding that marker's dosage for every participant
    (zero-padded past the real participant count). This is exactly what the
    `encrypt` stage produces — one plaintext (then ciphertext) per marker."""
    n_participants, n_markers = genotypes.shape
    assert n_participants <= n_slots, "participants exceed one batch; use batches"
    cols = []
    for m in range(n_markers):
        v = np.zeros(n_slots, dtype=np.float64)
        v[:n_participants] = genotypes[:, m]
        cols.append(v)
    return cols


def twin_scores(genotypes, weight, scaling=SCALING, noise_sd=0.0, rng=None):
    """Run the exact circuit shape in plaintext with per-operation
    quantization. Optionally inject per-slot Gaussian noise of the given sd to
    probe the application's tolerance to encryption noise."""
    g = quantize(genotypes, scaling)
    w = quantize(weight, scaling)
    n_participants, n_markers = g.shape
    acc = np.zeros(n_participants, dtype=np.float64)
    for m in range(n_markers):
        # one cipher x plaintext-scalar multiply, then rescale (a quantize)
        acc += quantize(g[:, m] * w[m], scaling)
    if noise_sd > 0.0:
        rng = rng or np.random.default_rng(0)
        acc = acc + rng.normal(0.0, noise_sd, n_participants)
    return acc


def decode_safety(worst_operand, scaling=SCALING, first_mod=FIRST_MOD,
                  depth=DEPTH, levels_used=LEVELS_USED, noise_margin=10):
    """Predict CKKS decode safety from the cleartext side (Stage 6 inequality):
        first_mod + (depth - levels)*scaling  >  scaling + log2(worst) + margin
    Returns (safe: bool, lhs_bits, rhs_bits)."""
    lhs = first_mod + (depth - levels_used) * scaling
    rhs = scaling + float(np.log2(max(worst_operand, 1e-12))) + noise_margin
    return lhs > rhs, lhs, rhs
