# Generated by the Niobium FHE Application Design AI Assistant (FHEanna). — v0.13.0
"""
validate_twin.py — Stage 7 gate: validate the faithful twin against the
plaintext reference before any encrypted code is built.

It reports the three things the methodology requires at the gate:
  1. task quality      — the reference PRS's AUC / stratification vs the
                         simulated phenotype (ground truth);
  2. twin vs reference — the cost of fixed-point quantization (should be ~0);
  3. decode safety     — the modulus-chain budget holds (Stage 6 inequality);
plus a noise-injection tolerance study that sets the objective pass criterion
for the later encrypted run (max encryption error that still flips zero
high-risk decisions).

Writes: data/reference_scores.csv, data/twin_scores.csv, data/twin_validation.json
"""

import csv
import json
import os
import numpy as np

import refmodel as R
import twin as T

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
HIGH_RISK_FRAC = 0.10     # "high genetic risk" = top decile


def main():
    meta = R.load_meta(os.path.join(DATA, "gen_meta.json"))
    G = R.load_genotypes(os.path.join(DATA, "genotypes.npy"))
    W = R.load_weights(os.path.join(DATA, "weights.csv"))
    L = R.load_labels(os.path.join(DATA, "labels.csv"))
    lo, hi = R.load_bounds(os.path.join(DATA, "marker_bounds.csv"))
    y = L["phenotype"]

    # client-side data hygiene (no-op on clean synthetic data)
    Gc = R.clip_dosages(G, lo, hi)

    ref = R.reference_scores(Gc, W["weight"])
    twin = T.twin_scores(Gc, W["weight"])

    # 1. task quality (reference vs ground-truth phenotype)
    auc = R.roc_auc(ref, y)
    ref_flags = R.top_fraction_flags(ref, HIGH_RISK_FRAC)
    top_case_rate = float(y[ref_flags].mean())

    # 2. twin vs reference
    abs_err = np.abs(twin - ref)
    twin_flags = R.top_fraction_flags(twin, HIGH_RISK_FRAC)
    twin_flip = int(np.sum(twin_flags != ref_flags))
    twin_spear = R.spearman(twin, ref)

    # 3. decode safety
    worst = float(np.max(np.abs(ref)))
    safe, lhs, rhs = T.decode_safety(worst)

    # noise-injection tolerance study: how much per-slot Gaussian noise can we
    # add before any high-risk (top-decile) decision flips?
    rng = np.random.default_rng(7)
    tol_grid = [1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 3e-2, 1e-1]
    max_noise_zero_flips = 0.0
    tol_rows = []
    for sd in tol_grid:
        noisy = T.twin_scores(Gc, W["weight"], noise_sd=sd, rng=rng)
        flips = int(np.sum(R.top_fraction_flags(noisy, HIGH_RISK_FRAC) != ref_flags))
        tol_rows.append({"noise_sd": sd, "high_risk_flips": flips})
        if flips == 0:
            max_noise_zero_flips = sd

    # pass tolerances for run_test: generous vs the tiny expected CKKS noise,
    # but far below the noise that would flip a decision.
    tol_twin = 1e-2
    tol_ref = 1e-2

    print("=" * 68)
    print("STAGE 7 TWIN VALIDATION: polygenic risk scoring")
    print("=" * 68)
    print(f"[data] {meta['n_participants']} participants x {meta['n_markers']} "
          f"markers (SYNTHETIC), prevalence {meta['realized_prevalence']:.3f}")
    print("-" * 68)
    print("1. TASK QUALITY  (reference PRS vs simulated phenotype)")
    print(f"   AUC                    = {auc:.4f}")
    print(f"   top-decile case rate   = {top_case_rate:.3f}  "
          f"(base rate {y.mean():.3f}, {top_case_rate/y.mean():.1f}x enrichment)")
    print("2. TWIN vs REFERENCE  (cost of fixed-point quantization)")
    print(f"   max |twin - ref|       = {abs_err.max():.3e}")
    print(f"   mean |twin - ref|      = {abs_err.mean():.3e}")
    print(f"   Spearman rank corr     = {twin_spear:.8f}")
    print(f"   high-risk flips        = {twin_flip}")
    print("3. DECODE SAFETY  (Stage 6 modulus-chain budget)")
    print(f"   worst |score|          = {worst:.3f}")
    print(f"   budget: {lhs:.1f} bits  >  need {rhs:.1f} bits  -> "
          f"{'SAFE' if safe else 'UNSAFE'}")
    print("4. NOISE TOLERANCE  (largest per-slot sd with zero high-risk flips)")
    for r in tol_rows:
        print(f"   sd={r['noise_sd']:.0e}: high-risk flips = {r['high_risk_flips']}")
    print(f"   -> tolerance (zero-flip)  = {max_noise_zero_flips:.0e}")
    print("-" * 68)

    gate = (abs_err.max() < 1e-6) and safe and twin_flip == 0
    print(f"GATE: {'PASS' if gate else 'FAIL'}. Twin reproduces the reference "
          f"and the circuit is decode-safe.")
    print("=" * 68)

    # ---- write artifacts --------------------------------------------------
    ids = L["participant_id"]
    with open(os.path.join(DATA, "reference_scores.csv"), "w", newline="") as fh:
        w = csv.writer(fh, lineterminator="\n"); w.writerow(["participant_id", "reference_score"])
        for i, s in zip(ids, ref):
            w.writerow([int(i), f"{s:.10g}"])
    with open(os.path.join(DATA, "twin_scores.csv"), "w", newline="") as fh:
        w = csv.writer(fh, lineterminator="\n"); w.writerow(["participant_id", "twin_score"])
        for i, s in zip(ids, twin):
            w.writerow([int(i), f"{s:.10g}"])

    out = {
        "task_quality": {"auc": float(auc), "top_decile_case_rate": top_case_rate,
                         "base_rate": float(y.mean())},
        "twin_vs_reference": {"max_abs_err": float(abs_err.max()),
                              "mean_abs_err": float(abs_err.mean()),
                              "spearman": float(twin_spear),
                              "high_risk_flips": twin_flip},
        "decode_safety": {"worst_operand": worst, "budget_bits": float(lhs),
                          "need_bits": float(rhs), "safe": bool(safe)},
        "noise_tolerance": {"grid": tol_rows,
                            "zero_flip_sd": float(max_noise_zero_flips),
                            "pass_tol_twin": tol_twin, "pass_tol_ref": tol_ref},
        "high_risk_frac": HIGH_RISK_FRAC,
        "params": {"ring_dim": 65536, "n_slots": T.N_SLOTS, "scaling": T.SCALING,
                   "first_mod": T.FIRST_MOD, "depth": T.DEPTH,
                   "levels_used": T.LEVELS_USED},
        "gate": "PASS" if gate else "FAIL",
    }
    with open(os.path.join(DATA, "twin_validation.json"), "w") as fh:
        json.dump(out, fh, indent=2)

    return 0 if gate else 1


if __name__ == "__main__":
    raise SystemExit(main())
