// Auto-generated by nbc — CLEARTEXT REFERENCE for stage: decrypt
// Same circuit, plaintext semantics. No crypto, no keys, no Niobium.
// DO NOT EDIT — changes will be overwritten

#include "nb_shared.h"

namespace nbref {

using CryptoParams = ::CryptoParamsRef;
using EncryptedMarkers = ::EncryptedMarkersRef;
using EncryptedScores = ::EncryptedScoresRef;


auto decrypt_scores(Instance inst, uint32_t batch_id) {
  auto sk = 0  /* no secret key in reference */;
  auto encrypted = [&]() { EncryptedScores _w; _w.scores = nb_plain::read_slots(fs::path((ctxtdowndir(inst) / (("cipher_scores_" + std::to_string(batch_id)) + ".bin"))).string() + ".ref"); return _w; }();
  auto scores = (encrypted.scores);
  return scores;
}

}  // namespace nbref

int main(int argc, char* argv[]) {
  if (argc < 2 || !std::isdigit(argv[1][0])) {
    std::cout << "Usage: " << argv[0] << " instance-size [options]\n";
    std::cout << "  Instance-size: 0-4\n";
    return 0;
  }

  auto size = static_cast<Profile>(std::stoi(argv[1]));
  auto inst = instance(size);

  for (int i = 2; i < argc; i++) {
    std::string arg = argv[i];
  }

  if (argc < 3 || !std::isdigit(argv[2][0])) {
    std::cerr << "Missing batch_id argument\n";
    return 1;
  }
  int batch_id = std::stoi(argv[2]);

  auto result = nbref::decrypt_scores(inst, batch_id);
  // Write plaintext result to disk
  auto _out_path = (root() / (("scores_batch_" + std::to_string(batch_id)) + ".bin"));
  fs::create_directories(_out_path.parent_path());
  write2disk(result, _out_path);

  return 0;
}
