// Auto-generated by nbc — stage: decrypt
// Domain: client
// DO NOT EDIT — changes will be overwritten

#include "nb_shared.h"

auto decrypt_scores(Instance inst, uint32_t batch_id) {
  auto sk = [&]() { auto _skpath = fs::path((keydir(inst) / "secret_key.bin")); CryptoContext<DCRTPoly> _cc; Serial::DeserializeFromFile(_skpath.parent_path() / "cc.bin", _cc, SerType::BINARY); PrivateKey<DCRTPoly> sk; Serial::DeserializeFromFile(_skpath, sk, SerType::BINARY); return sk; }();
  auto encrypted = [&]() { EncryptedScores _w; Ciphertext<DCRTPoly> _ct; Serial::DeserializeFromFile(fs::path((ctxtdowndir(inst) / (("cipher_scores_" + std::to_string(batch_id)) + ".bin"))), _ct, SerType::BINARY); _w.scores = _ct; return _w; }();
  auto scores = [&]() { Plaintext pt; sk->GetCryptoContext()->Decrypt(sk, encrypted.scores, &pt); return pt->GetRealPackedValue(); }();
  return scores;
}

int main(int argc, char* argv[]) {
  if (argc < 2 || !std::isdigit(argv[1][0])) {
    std::cout << "Usage: " << argv[0] << " instance-size [options]\n";
    std::cout << "  Instance-size: 0-4\n";
    return 0;
  }

  auto size = static_cast<Profile>(std::stoi(argv[1]));
  auto inst = instance(size);

  for (int i = 2; i < argc; i++) {
    std::string arg = argv[i];
  }

  if (argc < 3 || !std::isdigit(argv[2][0])) {
    std::cerr << "Missing batch_id argument\n";
    return 1;
  }
  int batch_id = std::stoi(argv[2]);

  auto result = decrypt_scores(inst, batch_id);
  // Write plaintext result to disk
  auto _out_path = (root() / (("scores_batch_" + std::to_string(batch_id)) + ".bin"));
  fs::create_directories(_out_path.parent_path());
  write2disk(result, _out_path);

  return 0;
}
