// Auto-generated by nbc — CLEARTEXT REFERENCE for stage: encrypt
// Same circuit, plaintext semantics. No crypto, no keys, no Niobium.
// DO NOT EDIT — changes will be overwritten

#include "nb_shared.h"

namespace nbref {

using CryptoParams = ::CryptoParamsRef;
using EncryptedMarkers = ::EncryptedMarkersRef;
using EncryptedScores = ::EncryptedScoresRef;


auto encrypt_markers(Instance inst, uint32_t batch_id) {
  auto params = CryptoParams{};
  auto dataset = read_text_matrix<double>((datadir(inst) / (("input_batch_" + std::to_string(batch_id)) + ".txt")), inst.n_markers);
  if (!((dataset.size() == inst.n_slots))) { throw std::runtime_error("batch must be padded to n_slots rows"); }
  return EncryptedMarkers{.markers = [&]() { std::vector<std::vector<double>> _result;
  for (auto m = 0; m < inst.n_markers; m++) {
    auto column = [&]() { auto& _m = dataset; std::remove_reference_t<decltype(_m[0])> _col; for (auto _k = 0; _k < inst.n_slots; _k++) _col.push_back(_m[_k][m]); return _col; }();
    _result.push_back(std::vector<double>(column.begin(), column.end()));
  }
  return _result; }()};
}

}  // namespace nbref

int main(int argc, char* argv[]) {
  if (argc < 2 || !std::isdigit(argv[1][0])) {
    std::cout << "Usage: " << argv[0] << " instance-size [options]\n";
    std::cout << "  Instance-size: 0-4\n";
    return 0;
  }

  auto size = static_cast<Profile>(std::stoi(argv[1]));
  auto inst = instance(size);

  for (int i = 2; i < argc; i++) {
    std::string arg = argv[i];
  }

  if (argc < 3 || !std::isdigit(argv[2][0])) {
    std::cerr << "Missing batch_id argument\n";
    return 1;
  }
  int batch_id = std::stoi(argv[2]);

  auto result = nbref::encrypt_markers(inst, batch_id);
  // Serialize EncryptedMarkers (field-type-driven layout)
  auto _dir = ctxtupdir(inst);
  fs::create_directories(_dir);
  for (size_t _i = 0; _i < result.markers.size(); _i++) {
    auto _fname = _dir / ("markers_" + std::to_string(_i) + ".ref.bin");
    nb_plain::write_slots(_fname, result.markers[_i]);
  }

  return 0;
}
