// Auto-generated by nbc — stage: keygen
// Domain: client
// DO NOT EDIT — changes will be overwritten

#include "nb_shared.h"

auto generate_keys(Instance inst) {
  auto keys = [&]() {
    CCParams<CryptoContextCKKSRNS> parameters;
    parameters.SetSecretKeyDist(UNIFORM_TERNARY);
    parameters.SetSecurityLevel(HEStd_128_classic);
    parameters.SetMultiplicativeDepth(2);
    parameters.SetScalingModSize(45);
    parameters.SetFirstModSize(60);
    parameters.SetRingDim(65536);
    parameters.SetScalingTechnique(FLEXIBLEAUTO);
    parameters.SetKeySwitchTechnique(HYBRID);
    auto cc = GenCryptoContext(parameters);
    cc->Enable(PKE); cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE); cc->Enable(ADVANCEDSHE);
    auto kp = cc->KeyGen();
    cc->EvalMultKeyGen(kp.secretKey);
    cc->EvalSumKeyGen(kp.secretKey);
    return kp;
  }();
  [&]() { auto _p = fs::path((keydir(inst) / "secret_key.bin")); fs::create_directories(_p.parent_path()); Serial::SerializeToFile(_p, keys.secretKey, SerType::BINARY); }();
  return CryptoParams{.context = keys.publicKey->GetCryptoContext(), .public_key = keys.publicKey};
}

int main(int argc, char* argv[]) {
  if (argc < 2 || !std::isdigit(argv[1][0])) {
    std::cout << "Usage: " << argv[0] << " instance-size [options]\n";
    std::cout << "  Instance-size: 0-4\n";
    return 0;
  }

  auto size = static_cast<Profile>(std::stoi(argv[1]));
  auto inst = instance(size);

  for (int i = 2; i < argc; i++) {
    std::string arg = argv[i];
  }

  auto result = generate_keys(inst);
  // Serialize CryptoParams to individual files
  auto _dir = keydir(inst);
  fs::create_directories(_dir);
  auto _cc = result.context;
  Serial::SerializeToFile(_dir / "cc.bin", _cc, SerType::BINARY);
  Serial::SerializeToFile(_dir / "pk.bin", result.public_key, SerType::BINARY);
  // Eval keys require stream-based serialization
  {
    std::ofstream mk_file(_dir / "mk.bin", std::ios::out | std::ios::binary);
    _cc->SerializeEvalMultKey(mk_file, SerType::BINARY);
  }
  {
    std::ofstream rk_file(_dir / "rk.bin", std::ios::out | std::ios::binary);
    _cc->SerializeEvalAutomorphismKey(rk_file, SerType::BINARY);
  }

  return 0;
}
