#ifndef NB_SHARED_H_
#define NB_SHARED_H_
// Auto-generated by nbc from .niob source files
// DO NOT EDIT — changes will be overwritten

#include <vector>
#include <string>
#include <filesystem>
#include <cmath>
#include <cassert>
#include <iostream>
#include <fstream>
#include <set>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <functional>

#include "openfhe.h"
#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"


using namespace lbcrypto;
namespace fs = std::filesystem;

// Utility: read a binary file into a vector of vectors
template<typename T>
std::vector<std::vector<T>> read2vecs(std::filesystem::path fname, int record_dim) {
  std::ifstream file(fname, std::ios::binary);
  if (!file.is_open()) throw std::runtime_error("Cannot open " + fname.string());
  file.seekg(0, std::ios::end);
  auto nbytes = file.tellg();
  file.seekg(0, std::ios::beg);
  auto nrecords = nbytes / (record_dim * sizeof(T));
  std::vector<std::vector<T>> result(nrecords);
  for (auto& r : result) {
    r.resize(record_dim);
    file.read(reinterpret_cast<char*>(r.data()), record_dim * sizeof(T));
  }
  return result;
}

template<typename T>
std::vector<T> read1vec(std::filesystem::path fname, int dim) {
  auto vecs = read2vecs<T>(fname, dim);
  if (vecs.empty()) return {};
  return vecs[0];
}

// Utility: read a text file (space-separated) into a vector of vectors
template<typename T>
std::vector<std::vector<T>> read_text_matrix(std::filesystem::path fname, int record_dim) {
  std::ifstream file(fname);
  if (!file.is_open()) throw std::runtime_error("Cannot open " + fname.string());
  std::vector<std::vector<T>> result;
  std::string line;
  while (std::getline(file, line)) {
    if (line.empty()) continue;
    std::istringstream iss(line);
    std::vector<T> row;
    T val;
    while (iss >> val) row.push_back(val);
    if ((int)row.size() >= record_dim) row.resize(record_dim);
    result.push_back(std::move(row));
  }
  return result;
}

template<typename T>
void write2disk(const std::vector<std::vector<T>>& data, std::filesystem::path fname) {
  std::ofstream file(fname, std::ios::binary);
  if (!file.is_open()) throw std::runtime_error("Cannot open " + fname.string());
  for (const auto& r : data)
    file.write(reinterpret_cast<const char*>(r.data()), r.size() * sizeof(T));
}

template<typename T>
void write2disk(const std::vector<T>& data, std::filesystem::path fname) {
  std::ofstream file(fname, std::ios::binary);
  if (!file.is_open()) throw std::runtime_error("Cannot open " + fname.string());
  file.write(reinterpret_cast<const char*>(data.data()), data.size() * sizeof(T));
}

template<typename T>
std::vector<std::vector<T>> transpose_matrix(const std::vector<std::vector<T>>& m) {
  if (m.empty()) return {};
  size_t rows = m.size(), cols = m[0].size();
  std::vector<std::vector<T>> result(cols, std::vector<T>(rows));
  for (size_t i = 0; i < rows; i++)
    for (size_t j = 0; j < cols; j++) result[j][i] = m[i][j];
  return result;
}

template<typename T>
std::vector<std::vector<std::vector<T>>> batch_rows(
    const std::vector<std::vector<T>>& data, size_t batch_size) {
  std::vector<std::vector<std::vector<T>>> result;
  for (size_t i = 0; i < data.size(); i += batch_size) {
    size_t end = std::min(i + batch_size, data.size());
    result.emplace_back(data.begin() + i, data.begin() + end);
  }
  return result;
}

template<typename T>
std::vector<T> tile(const std::vector<T>& v, size_t n) {
  std::vector<T> result(n);
  for (size_t i = 0; i < n; i++) result[i] = v[i % v.size()];
  return result;
}

template<typename T, typename V>
std::vector<std::vector<T>> prepend_column(
    const std::vector<std::vector<T>>& data, V val) {
  std::vector<std::vector<T>> result;
  for (const auto& row : data) {
    std::vector<T> r = {static_cast<T>(val)};
    r.insert(r.end(), row.begin(), row.end());
    result.push_back(r);
  }
  return result;
}

template<typename T>
std::vector<std::vector<std::vector<double>>> scale_batched(
    const std::vector<std::vector<std::vector<T>>>& batches, double factor) {
  std::vector<std::vector<std::vector<double>>> result;
  for (auto& batch : batches) {
    result.push_back({});
    for (auto& row : batch) {
      result.back().push_back({});
      for (auto& val : row) result.back().back().push_back(val * factor);
    }
  }
  return result;
}

namespace nb_plain {
struct NoCrypto {};  // inert stand-in for key/context fields
using Slots = std::vector<double>;
inline Slots add(Slots a, const Slots& b) {
  if (a.size() < b.size()) a.resize(b.size(), 0.0);
  for (size_t i = 0; i < b.size(); ++i) a[i] += b[i]; return a; }
inline Slots add(Slots a, double s) { for (auto& x : a) x += s; return a; }
inline Slots sub(Slots a, const Slots& b) {
  if (a.size() < b.size()) a.resize(b.size(), 0.0);
  for (size_t i = 0; i < b.size(); ++i) a[i] -= b[i]; return a; }
inline Slots sub(Slots a, double s) { for (auto& x : a) x -= s; return a; }
inline Slots mul(const Slots& a, const Slots& b) {
  Slots r(std::min(a.size(), b.size()));
  for (size_t i = 0; i < r.size(); ++i) r[i] = a[i] * b[i]; return r; }
inline Slots mul(Slots a, double s) { for (auto& x : a) x *= s; return a; }
inline Slots nullsafe_add(const Slots& a, const Slots& b) {
  return a.empty() ? b : add(a, b); }
inline Slots negate(Slots a) { for (auto& x : a) x = -x; return a; }
inline Slots rotate(Slots a, int k) {  // EvalRotate: +k rotates left
  if (a.empty()) return a;
  k = ((k % (int)a.size()) + (int)a.size()) % (int)a.size();
  std::rotate(a.begin(), a.begin() + k, a.end()); return a; }
inline Slots slot_sum(const Slots& a, size_t n) {  // EvalSum semantics
  double s = 0.0;
  for (size_t i = 0; i < std::min(n, a.size()); ++i) s += a[i];
  return Slots(a.empty() ? n : a.size(), s); }
template <typename F> inline Slots apply(Slots a, F f) {
  for (auto& x : a) x = f(x); return a; }
inline Slots read_slots(const std::filesystem::path& p) {
  std::ifstream f(p, std::ios::binary);
  if (!f.is_open()) throw std::runtime_error("cannot open " + p.string());
  f.seekg(0, std::ios::end); auto n = f.tellg() / sizeof(double);
  f.seekg(0, std::ios::beg); Slots v(n);
  f.read(reinterpret_cast<char*>(v.data()), n * sizeof(double)); return v; }
inline void write_slots(const std::filesystem::path& p, const Slots& v) {
  std::filesystem::create_directories(p.parent_path());
  std::ofstream f(p, std::ios::binary);
  f.write(reinterpret_cast<const char*>(v.data()), v.size() * sizeof(double)); }
}  // namespace nb_plain

inline Ciphertext<DCRTPoly> NullSafeEvalAdd(
    CryptoContext<DCRTPoly> cc, Ciphertext<DCRTPoly> a, Ciphertext<DCRTPoly> b) {
  if (a == nullptr) return b;
  return cc->EvalAdd(a, b);
}

inline std::vector<double> slot_mask(size_t n_slots, size_t n_cols,
                                     size_t row_start, size_t row_end) {
  std::vector<double> mask(n_slots, 0.0);
  for (size_t col = 0; col < n_cols; col++)
    for (size_t row = row_start; row < row_end; row++)
      mask[col + row * n_cols] = 1.0;
  return mask;
}

inline std::filesystem::path root() {
  // Returns the project root directory
  auto p = std::filesystem::current_path();
  return p;
}

template<typename T>
std::vector<T> vector_union(std::vector<std::vector<T>>& vecs) {
  std::set<T> s;
  for (const auto& v : vecs) s.insert(v.begin(), v.end());
  return std::vector<T>(s.begin(), s.end());
}

constexpr uint32_t N_MARKERS = 2000;

enum Profile {
  Full = 0
};

struct Instance {
  Profile profile;
  uint32_t ring_dim;
  uint32_t n_slots;
  uint32_t n_markers;
  uint32_t depth;
};

struct CryptoParams {
  CryptoContext<DCRTPoly> context;
  PublicKey<DCRTPoly> public_key;
};

struct EncryptedMarkers {
  std::vector<Ciphertext<DCRTPoly>> markers;
};

struct EncryptedScores {
  Ciphertext<DCRTPoly> scores;
};

struct CryptoParamsRef {
  nb_plain::NoCrypto context;
  nb_plain::NoCrypto public_key;
  nb_plain::NoCrypto eval_mult_key;
};

struct EncryptedMarkersRef {
  std::vector<std::vector<double>> markers;
};

struct EncryptedScoresRef {
  std::vector<double> scores;
};

Instance instance(Profile profile);
std::filesystem::path keydir(Instance inst);
std::filesystem::path datadir(Instance inst);
std::filesystem::path modeldir(Instance inst);
std::filesystem::path ctxtupdir(Instance inst);
std::filesystem::path ctxtdowndir(Instance inst);
std::filesystem::path upload_batch_dir(Instance inst, uint32_t batch_id);
Ciphertext<DCRTPoly> prs_circuit(CryptoContext<DCRTPoly> cc, Instance inst, std::vector<Ciphertext<DCRTPoly>> x, std::vector<std::vector<double>> W);

#endif  // NB_SHARED_H_
