// Auto-generated by nbc from .niob source files
#include "nb_shared.h"

Instance instance(Profile profile) {
  switch (profile) {
    case Full: {
      return Instance{.profile = profile, .ring_dim = 65536, .n_slots = 32768, .n_markers = N_MARKERS, .depth = 2};
      break;
    }
    default: __builtin_unreachable();
  }
}

std::filesystem::path keydir(Instance inst) {
  return (root() / "keys");
}

std::filesystem::path datadir(Instance inst) {
  return (root() / "data");
}

std::filesystem::path modeldir(Instance inst) {
  return (root() / "model");
}

std::filesystem::path ctxtupdir(Instance inst) {
  return (root() / "upload");
}

std::filesystem::path ctxtdowndir(Instance inst) {
  return (root() / "download");
}

std::filesystem::path upload_batch_dir(Instance inst, uint32_t batch_id) {
  return (ctxtupdir(inst) / ("batch_" + std::to_string(batch_id)));
}

Ciphertext<DCRTPoly> prs_circuit(CryptoContext<DCRTPoly> cc, Instance inst, std::vector<Ciphertext<DCRTPoly>> x, std::vector<std::vector<double>> W) {
  Ciphertext<DCRTPoly> out;  // initialized to null
  for (auto m = 0; m < inst.n_markers; m++) {
    out = NullSafeEvalAdd(cc, out, cc->EvalMult(x[m], W[m][0]));
  }
  return out;
}

