// Auto-generated by nbc — stage: score
// Domain: server
// DO NOT EDIT — changes will be overwritten

#include "nb_shared.h"

#include "niobium/compiler.h"

static bool _nb_hollow_record = false;

auto score_batch(CryptoContext<DCRTPoly> cc, Instance inst, uint32_t batch_id) {
  auto params = CryptoParams{};
  auto em = [&]() { EncryptedMarkers _w; fs::path _dir = fs::path(upload_batch_dir(inst, batch_id)); for (int _i = 0; ; _i++) { auto _f = _dir / ("markers_" + std::to_string(_i) + ".bin"); if (!fs::exists(_f)) break; Ciphertext<DCRTPoly> _ct; Serial::DeserializeFromFile(_f, _ct, SerType::BINARY); _w.markers.push_back(_ct); } return _w; }();
  if (!niobium::compiler().is_cache_valid()) {
    std::cout << "[nb] Recording OpenFHE operations" << std::endl;
    niobium::compiler().enable_hollow_mode(_nb_hollow_record);
    niobium::compiler().start();
  }

  auto W = read_text_matrix<double>((modeldir(inst) / "weights.txt"), 1);
  auto scores = prs_circuit(cc, inst, em.markers, W);
  return EncryptedScores{.scores = std::const_pointer_cast<CiphertextImpl<DCRTPoly>>(scores)};
}

int main(int argc, char* argv[]) {
  niobium::compiler().init(argc, argv);

  if (argc < 2 || !std::isdigit(argv[1][0])) {
    std::cout << "Usage: " << argv[0] << " instance-size [options]\n";
    std::cout << "  Instance-size: 0-4\n";
    return 0;
  }

  auto size = static_cast<Profile>(std::stoi(argv[1]));
  auto inst = instance(size);

  bool hollow_record = niobium::compiler().is_hollow_mode();
  for (int i = 2; i < argc; i++) {
    std::string arg = argv[i];
  }

  if (argc < 3 || !std::isdigit(argv[2][0])) {
    std::cerr << "Missing batch_id argument\n";
    return 1;
  }
  int batch_id = std::stoi(argv[2]);

  niobium::compiler().enable_auto_tagging();
  niobium::Compiler::CacheParameters nb_params;
  nb_params.push_back({"profile", argv[1]});
  nb_params.push_back({"batch_id", argv[2]});
  niobium::compiler().cache_parameters(nb_params);
  niobium::compiler().set_program_info("score", "1.0", "Auto-generated from nb DSL");
  niobium::compiler().set_build_info(__FILE__, __LINE__, __TIMESTAMP__);

  // Load crypto context and keys from disk
  CryptoContext<DCRTPoly> cc;
  if (!Serial::DeserializeFromFile(keydir(inst) / "cc.bin", cc, SerType::BINARY)) {
    throw std::runtime_error("Failed to load CryptoContext");
  }

  PublicKey<DCRTPoly> pk;
  if (!Serial::DeserializeFromFile(keydir(inst) / "pk.bin", pk, SerType::BINARY)) {
    throw std::runtime_error("Failed to load PublicKey");
  }

  std::ifstream evalmult_file(keydir(inst) / "mk.bin", std::ios::in | std::ios::binary);
  if (!evalmult_file.is_open() || !cc->DeserializeEvalMultKey(evalmult_file, SerType::BINARY)) {
    throw std::runtime_error("Failed to load EvalMult key");
  }

  std::ifstream evalautomorphism_file(keydir(inst) / "rk.bin", std::ios::in | std::ios::binary);
  if (!evalautomorphism_file.is_open() || !cc->DeserializeEvalAutomorphismKey(evalautomorphism_file, SerType::BINARY)) {
    throw std::runtime_error("Failed to load EvalAutomorphism key");
  }

  _nb_hollow_record = hollow_record;

  const bool _nb_replaying = niobium::compiler().is_cache_valid();
  EncryptedScores result;
  if (!_nb_replaying) {
    result = score_batch(cc, inst, batch_id);
    niobium::compiler().probe("result", result.scores);
    niobium::compiler().stop();
    niobium::compiler().enable_hollow_mode(false);
  } else {
    std::cout << "[nb] Cached trace found — replaying (no FHE ops)" << std::endl;
    if (!niobium::compiler().replay()) {
      std::cerr << "[ERROR] FHETCH replay failed!" << std::endl;
      return 1;
    }
    if (!niobium::compiler().result(cc, "result", result.scores)) {
      std::cerr << "[ERROR] Result retrieval failed!" << std::endl;
      return 1;
    }
  }
  // Serialize EncryptedScores[batch_id]
  auto _idir = ctxtdowndir(inst);
  fs::create_directories(_idir);
  Serial::SerializeToFile(_idir / ("cipher_scores_" + std::to_string(batch_id) + ".bin"), result.scores, SerType::BINARY);

  return 0;
}
