// Auto-generated by nbc — CLEARTEXT REFERENCE for stage: score
// Same circuit, plaintext semantics. No crypto, no keys, no Niobium.
// DO NOT EDIT — changes will be overwritten

#include "nb_shared.h"

namespace nbref {

using CryptoParams = ::CryptoParamsRef;
using EncryptedMarkers = ::EncryptedMarkersRef;
using EncryptedScores = ::EncryptedScoresRef;

std::vector<double> prs_circuit(Instance inst, std::vector<std::vector<double>> x, std::vector<std::vector<double>> W);

std::vector<double> prs_circuit(Instance inst, std::vector<std::vector<double>> x, std::vector<std::vector<double>> W) {
  std::vector<double> out = std::vector<double>{};
  for (auto m = 0; m < inst.n_markers; m++) {
    out = nb_plain::nullsafe_add(out, nb_plain::mul(x[m], W[m][0]));
  }
  return out;
}

auto score_batch(Instance inst, uint32_t batch_id) {
  auto params = CryptoParams{};
  auto em = [&]() { EncryptedMarkers _w; fs::path _dir = fs::path(upload_batch_dir(inst, batch_id)); for (int _i = 0; ; _i++) { auto _f = _dir / ("markers_" + std::to_string(_i) + ".ref.bin"); if (!fs::exists(_f)) break; _w.markers.push_back(nb_plain::read_slots(_f)); } return _w; }();
  auto W = read_text_matrix<double>((modeldir(inst) / "weights.txt"), 1);
  auto scores = prs_circuit(inst, em.markers, W);
  return EncryptedScores{.scores = scores};
}

}  // namespace nbref

int main(int argc, char* argv[]) {
  if (argc < 2 || !std::isdigit(argv[1][0])) {
    std::cout << "Usage: " << argv[0] << " instance-size [options]\n";
    std::cout << "  Instance-size: 0-4\n";
    return 0;
  }

  auto size = static_cast<Profile>(std::stoi(argv[1]));
  auto inst = instance(size);

  for (int i = 2; i < argc; i++) {
    std::string arg = argv[i];
  }

  if (argc < 3 || !std::isdigit(argv[2][0])) {
    std::cerr << "Missing batch_id argument\n";
    return 1;
  }
  int batch_id = std::stoi(argv[2]);

  auto result = nbref::score_batch(inst, batch_id);
  // Serialize EncryptedScores[batch_id]
  auto _idir = ctxtdowndir(inst);
  fs::create_directories(_idir);
  Serial::SerializeToFile(_idir / ("cipher_scores_" + std::to_string(batch_id) + ".bin"), result.scores, SerType::BINARY);

  return 0;
}
